blog/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :posts

  post 'posts/new'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/post.rb
class Post < ApplicationRecord
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.first(5)
  end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @posts = Post.new
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    @post.save
    redirect_to @post
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to "/"
  end

  private
    def post_params
      params.require(:post).permit(:title, :text)
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/home/index.html.erb
<h1>Home</h1>

<table>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Create', post_path('new') %>
<%= link_to 'All', 'posts' %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/posts/index.html.erb
<table>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'delete', [post], method: :delete, data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
</table>


<%= link_to 'Create', post_path('new') %>

blog/app/views/posts/new.html.erb
<%= form_with scope: :post, url: posts_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

blog/app/views/posts/show.html.erb
<p>
  title
  <%= @post.title %>
</P>

<p>
  text
  <%= @post.text %>
</p>


<%= link_to 'Create', post_path('new') %>

<%= link_to 'Home', '/' %>